### OHE(One Hot Encoding)

In [12]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [13]:
## Create a sample DataFrame
df = pd.DataFrame({
    'Color': ['Red', 'Blue', 'Green', 'Green','Red','Blue']
})
df.head()

   Color
0    Red
1   Blue
2  Green
3  Green
4    Red

In [14]:
## Craete an instance of OneHotEncoder
encoder = OneHotEncoder()

In [21]:
## Perform fit and transform
encoded = encoder.fit_transform(df[['Color']]).toarray()

import pandas as pd 
encoder_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out())
encoder_df

   Color_Blue  Color_Green  Color_Red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [22]:
## For New Data
encoder.transform([['Blue']]).toarray()
pd.concat([df,encoder_df],axis = 1)

c:\Users\gp298\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Color  Color_Blue  Color_Green  Color_Red
0    Red         0.0          0.0        1.0
1   Blue         1.0          0.0        0.0
2  Green         0.0          1.0        0.0
3  Green         0.0          1.0        0.0
4    Red         0.0          0.0        1.0
5   Blue         1.0          0.0        0.0

In [28]:
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]