In [1]:
import pandas as pd
## Create a sample DataFrame with a categorical variable and a target variable
df = pd.DataFrame({
    'city': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    'price': [100, 80, 60, 70, 90]
})
df

          city  price
0     New York    100
1  Los Angeles     80
2      Chicago     60
3      Houston     70
4      Phoenix     90

In [2]:
mean_price = df.groupby('city')['price'].mean().to_dict()
mean_price

{'Chicago': 60.0,
 'Houston': 70.0,
 'Los Angeles': 80.0,
 'New York': 100.0,
 'Phoenix': 90.0}

In [3]:
df['city_encoded'] = df['city'].map(mean_price)
df

          city  price  city_encoded
0     New York    100         100.0
1  Los Angeles     80          80.0
2      Chicago     60          60.0
3      Houston     70          70.0
4      Phoenix     90          90.0

In [4]:
df[['price','city_encoded']]

   price  city_encoded
0    100         100.0
1     80          80.0
2     60          60.0
3     70          70.0
4     90          90.0

In [5]:
import seaborn as sns
sns.load_dataset("tips")

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]