In [26]:
import pandas as pd

df = pd.read_csv("sales_data.csv")
## Fetch 1st 5 Rows
df.head(5)
df.tail(5)
df.describe()
df.dtypes

OrderID      int64
Year         int64
Region      object
Product     object
Category    object
Quantity     int64
Price        int64
Sales        int64
Profit       int64
dtype: object

In [27]:
## Handling Missing Values
df.isnull()
df[df.isnull()]
df.isnull().any(axis = 1)
df.isnull().sum()
df.fillna(0)
df_filled = df.fillna(0)
df_filled

,OrderID,Year,Region,Product,Category,Quantity,Price,Sales,Profit
0,1001,2016,East,Laptop,Electronics,2,60000,120000,20000
1,1002,2017,West,Phone,Electronics,5,20000,100000,15000
2,1003,2018,North,Tablet,Electronics,3,30000,90000,12000
3,1004,2019,South,Laptop,Electronics,1,65000,65000,10000
4,1005,2020,East,Phone,Electronics,4,22000,88000,13000
5,1006,2021,West,Tablet,Electronics,2,31000,62000,11000
6,1007,2022,North,Monitor,Electronics,3,15000,45000,8000
7,1008,2023,South,Headphones,Accessories,6,5000,30000,6000
8,1009,2024,East,Laptop,Electronics,1,70000,70000,12000
9,1010,2025,West,Phone,Electronics,3,21000,63000,9000
10,1011,2026,North,Tablet,Electronics,2,28000,56000,7000
11,1012,2016,South,Monitor,Electronics,4,14000,56000,9500
12,1013,2017,East,Headphones,Accessories,5,4500,22500,5000
13,1014,2018,West,Laptop,Electronics,2,62000,124000,21000
14,1015,2019,North,Phone,Electronics,6,19000,114000,18000
15,1016,2020,South,Tablet,Electronics,3,32000,96000,14000
16,1017,2021,East,Monitor,Electronics,2,16000,32000,6000
17,1018,2022,West,Headphones,Accessories,7,4800,33600,5500
18,1019,2023,North,Laptop,Electronics,1,68000,68000,11000
19,1020,2024,South,Phone,Electronics,4,23000,92000,15000
20,1021,2025,East,Tablet,Electronics,2,30000,60000,8000
21,1022,2026,West,Monitor,Electronics,3,15500,46500,7500
22,1023,2016,North,Headphones,Accessories,5,5200,26000,4500
23,1024,2017,South,Laptop,Electronics,2,64000,128000,22000
24,1025,2018,East,Phone,Electronics,3,21000,63000,10000
25,1026,2019,West,Tablet,Electronics,4,29000,116000,16000
26,1027,2020,North,Monitor,Electronics,2,15000,30000,5000
27,1028,2021,South,Headphones,Accessories,6,4700,28200,4800
28,1029,2022,East,Laptop,Electronics,1,72000,72000,13000
29,1030,2023,West,Phone,Electronics,5,20000,100000,17000
30,1031,2024,North,Tablet,Electronics,3,31000,93000,12000
31,1032,2025,South,Monitor,Electronics,4,14500,58000,9000
32,1033,2026,East,Headphones,Accessories,5,5000,25000,6000
33,1034,2016,West,Laptop,Electronics,2,63000,126000,20000
34,1035,2017,North,Phone,Electronics,4,22000,88000,14000
35,1036,2018,South,Tablet,Electronics,3,30000,90000,13000
36,1037,2019,East,Monitor,Electronics,2,15500,31000,5000
37,1038,2020,West,Headphones,Accessories,6,4900,29400,5200
38,1039,2021,North,Laptop,Electronics,1,69000,69000,12000
39,1040,2022,South,Phone,Electronics,5,21000,105000,16000
40,1041,2023,East,Tablet,Electronics,2,28000,56000,7000
41,1042,2024,West,Monitor,Electronics,3,15000,45000,8000
42,1043,2025,North,Headphones,Accessories,4,5300,21200,4000
43,1044,2026,South,Laptop,Electronics,2,66000,132000,23000
44,1045,2016,East,Phone,Electronics,3,20000,60000,9000
45,1046,2017,West,Tablet,Electronics,4,31000,124000,17000
46,1047,2018,North,Monitor,Electronics,2,16000,32000,6000
47,1048,2019,South,Headphones,Accessories,5,4800,24000,4500
48,1049,2020,East,Laptop,Electronics,1,71000,71000,12000
49,1050,2021,West,Phone,Electronics,4,22000,88000,15000

In [28]:
## Filling Missing Values with the Mean of the Column
df["Sales_Fill_NA"] = df["Sales"].fillna(df['Sales'].mean())
df

,OrderID,Year,Region,Product,Category,Quantity,Price,Sales,Profit,Sales_Fill_NA
0,1001,2016,East,Laptop,Electronics,2,60000,120000,20000,120000
1,1002,2017,West,Phone,Electronics,5,20000,100000,15000,100000
2,1003,2018,North,Tablet,Electronics,3,30000,90000,12000,90000
3,1004,2019,South,Laptop,Electronics,1,65000,65000,10000,65000
4,1005,2020,East,Phone,Electronics,4,22000,88000,13000,88000
5,1006,2021,West,Tablet,Electronics,2,31000,62000,11000,62000
6,1007,2022,North,Monitor,Electronics,3,15000,45000,8000,45000
7,1008,2023,South,Headphones,Accessories,6,5000,30000,6000,30000
8,1009,2024,East,Laptop,Electronics,1,70000,70000,12000,70000
9,1010,2025,West,Phone,Electronics,3,21000,63000,9000,63000
10,1011,2026,North,Tablet,Electronics,2,28000,56000,7000,56000
11,1012,2016,South,Monitor,Electronics,4,14000,56000,9500,56000
12,1013,2017,East,Headphones,Accessories,5,4500,22500,5000,22500
13,1014,2018,West,Laptop,Electronics,2,62000,124000,21000,124000
14,1015,2019,North,Phone,Electronics,6,19000,114000,18000,114000
15,1016,2020,South,Tablet,Electronics,3,32000,96000,14000,96000
16,1017,2021,East,Monitor,Electronics,2,16000,32000,6000,32000
17,1018,2022,West,Headphones,Accessories,7,4800,33600,5500,33600
18,1019,2023,North,Laptop,Electronics,1,68000,68000,11000,68000
19,1020,2024,South,Phone,Electronics,4,23000,92000,15000,92000
20,1021,2025,East,Tablet,Electronics,2,30000,60000,8000,60000
21,1022,2026,West,Monitor,Electronics,3,15500,46500,7500,46500
22,1023,2016,North,Headphones,Accessories,5,5200,26000,4500,26000
23,1024,2017,South,Laptop,Electronics,2,64000,128000,22000,128000
24,1025,2018,East,Phone,Electronics,3,21000,63000,10000,63000
25,1026,2019,West,Tablet,Electronics,4,29000,116000,16000,116000
26,1027,2020,North,Monitor,Electronics,2,15000,30000,5000,30000
27,1028,2021,South,Headphones,Accessories,6,4700,28200,4800,28200
28,1029,2022,East,Laptop,Electronics,1,72000,72000,13000,72000
29,1030,2023,West,Phone,Electronics,5,20000,100000,17000,100000
30,1031,2024,North,Tablet,Electronics,3,31000,93000,12000,93000
31,1032,2025,South,Monitor,Electronics,4,14500,58000,9000,58000
32,1033,2026,East,Headphones,Accessories,5,5000,25000,6000,25000
33,1034,2016,West,Laptop,Electronics,2,63000,126000,20000,126000
34,1035,2017,North,Phone,Electronics,4,22000,88000,14000,88000
35,1036,2018,South,Tablet,Electronics,3,30000,90000,13000,90000
36,1037,2019,East,Monitor,Electronics,2,15500,31000,5000,31000
37,1038,2020,West,Headphones,Accessories,6,4900,29400,5200,29400
38,1039,2021,North,Laptop,Electronics,1,69000,69000,12000,69000
39,1040,2022,South,Phone,Electronics,5,21000,105000,16000,105000
40,1041,2023,East,Tablet,Electronics,2,28000,56000,7000,56000
41,1042,2024,West,Monitor,Electronics,3,15000,45000,8000,45000
42,1043,2025,North,Headphones,Accessories,4,5300,21200,4000,21200
43,1044,2026,South,Laptop,Electronics,2,66000,132000,23000,132000
44,1045,2016,East,Phone,Electronics,3,20000,60000,9000,60000
45,1046,2017,West,Tablet,Electronics,4,31000,124000,17000,124000
46,1047,2018,North,Monitor,Electronics,2,16000,32000,6000,32000
47,1048,2019,South,Headphones,Accessories,5,4800,24000,4500,24000
48,1049,2020,East,Laptop,Electronics,1,71000,71000,12000,71000
49,1050,2021,West,Phone,Electronics,4,22000,88000,15000,88000

In [31]:
### Renaming Columns
df = df.rename(columns = {"Sales" : "Sales_data"})
df.head(5)

,OrderID,Year,Region,Product,Category,Quantity,Price,Sales_data,Profit,Sales_Fill_NA
0,1001,2016,East,Laptop,Electronics,2,60000,120000,20000,120000
1,1002,2017,West,Phone,Electronics,5,20000,100000,15000,100000
2,1003,2018,North,Tablet,Electronics,3,30000,90000,12000,90000
3,1004,2019,South,Laptop,Electronics,1,65000,65000,10000,65000
4,1005,2020,East,Phone,Electronics,4,22000,88000,13000,88000

In [43]:
## Change Data Type
df["Price_new"] = df["Price"].astype(float)
df["Price_new"] = df["Price"].fillna(df["Price"].mean().astype(float))

df["New_price"] = df["Price"].apply(lambda x:x*2)
df.head()

,OrderID,Year,Region,Product,Category,Quantity,Price,Sales_data,Profit,Sales_Fill_NA,Price_new,New_price
0,1001,2016,East,Laptop,Electronics,2,60000,120000,20000,120000,60000,120000
1,1002,2017,West,Phone,Electronics,5,20000,100000,15000,100000,20000,40000
2,1003,2018,North,Tablet,Electronics,3,30000,90000,12000,90000,30000,60000
3,1004,2019,South,Laptop,Electronics,1,65000,65000,10000,65000,65000,130000
4,1005,2020,East,Phone,Electronics,4,22000,88000,13000,88000,22000,44000

In [54]:
## Data Aggrigating And Groping
grouped_mean = df.groupby("Product")["Price"].mean()
grouped_mean

grouped_sum = df.groupby(["Product","Region"])["Price"].sum()
grouped_sum

grouped_mean = df.groupby(["Product","Region"])["Price"].sum()
grouped_mean

### Multiple Aggrigate Function
grouped_agg = df.groupby("Region")["Price"].agg(["mean","sum","count"])
grouped_agg

                mean     sum  count
Region
East    33461.538462  435000     13
North   26958.333333  323500     12
South   28666.666667  344000     12
West    26092.307692  339200     13

In [58]:
### Merging and Joining DataFrames
## Create Sample DataFrames
df1 = pd.DataFrame({"key" : ["A","B","C","D"],
                    "Value1" : [1,2,3,4]})
df2 = pd.DataFrame({"key" : ["A","B","C","D"],
                    "Value2" : [5,6,7,8]})

# Merge DataFrame an the "Key Columns"
pd.merge(df1,df2,on = "key", how = "inner")

  key  Value1  Value2
0   A       1       5
1   B       2       6
2   C       3       7
3   D       4       8